# Generated by Django 4.1.7 on 2023-04-06 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation_fournisseur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=128)),
                ('raison_sociale', models.CharField(max_length=128)),
                ('pays', models.CharField(max_length=25)),
                ('ville', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=12, unique=True)),
                ('devise', models.IntegerField(choices=[(1, 'GNF'), (2, 'USD')])),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comptes_clients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_comptes_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField()),
                ('carrat', models.IntegerField()),
                ('densite', models.FloatField()),
                ('prix_unit_vente', models.BigIntegerField()),
                ('montant', models.BigIntegerField()),
                ('fixing_bourse', models.FloatField()),
                ('discompte', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée'), (3, 'Annulée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ventes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_ventes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCompteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.IntegerField(choices=[(1, 'Paiement'), (2, 'Avancer'), (3, 'Entrée'), (4, 'Sortie')])),
                ('montant', models.BigIntegerField()),
                ('taux', models.FloatField(null=True)),
                ('motif', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée'), (3, 'Annulée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('compte_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.compteclient')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_operations_comptes_clients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_operations_comptes_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactureExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_exp', models.FloatField()),
                ('slug', models.CharField(max_length=12)),
                ('carrat_moyen', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_factures_expeditions', to=settings.AUTH_USER_MODEL)),
                ('fournisseur_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fournisseur')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_factures_expeditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée'), (3, 'Annulée')], default=1)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('client_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expeditions', to=settings.AUTH_USER_MODEL)),
                ('facture_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.factureexpedition')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_expeditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
