# Generated by Django 4.1.7 on 2023-04-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
