# Generated by Django 4.1.7 on 2023-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0002_alter_expedition_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationcompteclient',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant',
        ),
        migrations.AlterField(
            model_name='factureexpedition',
            name='carrat_moyen',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='carrat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_unit_vente',
            field=models.FloatField(),
        ),
    ]
