# Generated by Django 4.1.7 on 2023-04-10 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_client', '0004_alter_client_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compteclient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_comptes_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factureexpedition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_factures_expeditions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationcompteclient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operations_comptes_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
