# Generated by Django 4.1.7 on 2023-04-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0011_remove_attribution_nombre_barre_and_more'),
        ('operation_client', '0005_alter_client_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='carrat',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='discompte',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='prix_unit_vente',
        ),
        migrations.AddField(
            model_name='vente',
            name='achat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achat_vente', to='operation_fournisseur.achat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='discount',
            field=models.FloatField(default='202315041622'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vente',
            name='densite',
            field=models.FloatField(default=22),
        ),
    ]
