# Generated by Django 4.1.7 on 2023-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0006_remove_vente_carrat_remove_vente_discompte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='carrat_moyen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='poids_fixe',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
