# Generated by Django 4.1.7 on 2023-04-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0012_achat_carra_moyen_achat_poids_total'),
        ('operation_client', '0007_vente_carrat_moyen_vente_poids_fixe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='achat',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='carrat_moyen',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='densite',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='poids_fixe',
        ),
        migrations.AddField(
            model_name='vente',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Vente par barres'), (2, 'Vente globale')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VenteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField()),
                ('carrat', models.FloatField()),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_client.vente')),
            ],
        ),
    ]
