# Generated by Django 4.1.7 on 2023-04-17 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0008_remove_vente_achat_remove_vente_carrat_moyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventedetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
