# Generated by Django 4.1.7 on 2023-04-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0011_remove_ventedetail_achat_remove_ventedetail_carrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcompteclient',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=20230421, max_digits=20),
            preserve_default=False,
        ),
    ]
