# Generated by Django 4.1.7 on 2023-05-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0028_caisse_fournisseur_caisse_montant_anterieur_and_more'),
        ('operation_client', '0012_operationcompteclient_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventedetail',
            name='achat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat'),
        ),
    ]
