# Generated by Django 4.1.7 on 2023-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0014_alter_factureexpedition_carrat_moyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureexpedition',
            name='poids_exp',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='operationcompteclient',
            name='taux',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
