# Generated by Django 4.1.7 on 2023-05-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0044_fixingdetail_carrat_moyen_restant'),
        ('operation_client', '0016_alter_factureexpedition_carrat_moyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='achat_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achatitems'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='code_exp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='lot_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.lotarrivage'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='type_envoie',
            field=models.IntegerField(choices=[(1, 'Lot'), (2, 'Achat'), (3, 'Details')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedition',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
