# Generated by Django 4.1.7 on 2023-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_client', '0020_alter_expedition_achat_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='achat',
        ),
    ]
