# Generated by Django 4.1.7 on 2023-04-06 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_part', models.CharField(max_length=12, unique=True)),
                ('devise', models.IntegerField(choices=[(1, 'GNF'), (2, 'USD')])),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_comptes_particuliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=40)),
                ('pays', models.CharField(max_length=25)),
                ('ville', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_particuliers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_particuliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.IntegerField(choices=[(1, 'Depôt'), (2, 'Retrait'), (3, 'Transfert')])),
                ('montant', models.BigIntegerField()),
                ('taux', models.FloatField(null=True)),
                ('motif', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée'), (3, 'Annulée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('compte_particulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.compteparticulier')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_operations_particuliers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_operations_particuliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compteparticulier',
            name='particulier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.particulier'),
        ),
        migrations.AddField(
            model_name='compteparticulier',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_comptes_particuliers', to=settings.AUTH_USER_MODEL),
        ),
    ]
