# Generated by Django 4.1.7 on 2023-04-10 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_alter_compteparticulier_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteparticulier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_comptes_particuliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationparticulier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operations_particuliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_particuliers', to=settings.AUTH_USER_MODEL),
        ),
    ]
