# Generated by Django 4.1.7 on 2023-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_compteparticulier_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationparticulier',
            name='taux',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
