# Generated by Django 4.1.7 on 2023-03-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_fournis', models.CharField(max_length=12, unique=True)),
                ('devise', models.IntegerField(choices=[(1, 'GNF'), (2, 'USD')])),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=40)),
                ('pays', models.CharField(max_length=25)),
                ('ville', models.CharField(max_length=25)),
                ('adresse', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Suspendu'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotArrivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=28)),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Clôturé'), (3, 'Supprimé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCompteFournis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.IntegerField(choices=[(1, 'Paiement'), (2, 'Avancer'), (3, 'Entrée'), (4, 'Sortie')])),
                ('montant', models.BigIntegerField()),
                ('taux', models.FloatField(null=True)),
                ('motif', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validée'), (3, 'Annulée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('compte_fournis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.comptefournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Fixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_fixe', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validé'), (3, 'Annulé')], default=1)),
                ('fixing_bourse', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='comptefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fournisseur'),
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_barre', models.IntegerField()),
                ('poids_achete', models.FloatField(null=True)),
                ('poids_vendu', models.FloatField(null=True)),
                ('poids_restant', models.FloatField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Placée')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('arrivage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.lotarrivage')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_achat', models.FloatField()),
                ('carrat_achat', models.IntegerField()),
                ('prix_unit_achat', models.BigIntegerField()),
                ('montant_achat', models.BigIntegerField()),
                ('slug', models.CharField(max_length=12)),
                ('status', models.IntegerField(choices=[(1, 'En cours'), (2, 'Validé')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fournisseur')),
            ],
        ),
    ]
