# Generated by Django 4.1.7 on 2023-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='montant_achat',
        ),
        migrations.RemoveField(
            model_name='operationcomptefournis',
            name='montant',
        ),
        migrations.AddField(
            model_name='achat',
            name='manquant',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='carrat_achat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='achat',
            name='prix_unit_achat',
            field=models.FloatField(),
        ),
    ]
