# Generated by Django 4.1.7 on 2023-04-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_fournisseur', '0002_remove_achat_montant_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_achats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_attributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comptefournisseur',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_comptes_fournisseurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixing',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_fixings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_fournisseurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotarrivage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_lots_arrivages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationcomptefournis',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_operations_comptes_fournis', to=settings.AUTH_USER_MODEL),
        ),
    ]
