# Generated by Django 4.1.7 on 2023-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0002_alter_fournisseur_email_alter_fournisseur_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotarrivage',
            name='designation',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
