# Generated by Django 4.1.7 on 2023-04-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_fournisseur', '0003_alter_achat_updated_by_alter_attribution_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_achats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comptefournisseur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_comptes_fournisseurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotarrivage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lots_arrivages', to=settings.AUTH_USER_MODEL),
        ),
    ]
