# Generated by Django 4.1.7 on 2023-04-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0005_alter_attribution_created_by_alter_fixing_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='carrat_achat',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='manquant',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='poids_achat',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='prix_unit_achat',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='achat',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name='AchatItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_achat', models.FloatField()),
                ('carrat_achat', models.FloatField()),
                ('manquant', models.FloatField(null=True)),
                ('achat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achat_achat_items', to='operation_fournisseur.achat')),
            ],
        ),
    ]
