# Generated by Django 4.1.7 on 2023-04-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0006_remove_achat_carrat_achat_remove_achat_manquant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatitems',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achat_achat_items', to='operation_fournisseur.achat'),
        ),
    ]
