# Generated by Django 4.1.7 on 2023-04-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0008_alter_achat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='slug',
        ),
    ]
