# Generated by Django 4.1.7 on 2023-04-12 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0009_remove_achat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
