# Generated by Django 4.1.7 on 2023-04-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0010_achat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='nombre_barre',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='poids_achete',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='poids_restant',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='poids_vendu',
        ),
        migrations.AddField(
            model_name='attribution',
            name='achat',
            field=models.ForeignKey(default=20231504, on_delete=django.db.models.deletion.CASCADE, related_name='achat_attribution', to='operation_fournisseur.achat'),
            preserve_default=False,
        ),
    ]
