# Generated by Django 4.1.7 on 2023-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0011_remove_attribution_nombre_barre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='carra_moyen',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achat',
            name='poids_total',
            field=models.FloatField(default=20230417),
            preserve_default=False,
        ),
    ]
