# Generated by Django 4.1.7 on 2023-04-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0013_remove_achat_carra_moyen_achat_carrat_moyen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='carrat_moyen',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='poids_total',
        ),
    ]
