# Generated by Django 4.1.7 on 2023-04-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0014_remove_achat_carrat_moyen_remove_achat_poids_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='carrat_moyen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='poids_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
