# Generated by Django 4.1.7 on 2023-04-21 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_fournisseur', '0015_achat_carrat_moyen_achat_poids_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcomptefournis',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=20230421, max_digits=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_total', models.FloatField()),
                ('carrat_moyen', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_facture_fournisseur', to=settings.AUTH_USER_MODEL)),
                ('fixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fixing')),
            ],
        ),
    ]
