# Generated by Django 4.1.7 on 2023-04-23 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_fournisseur', '0016_operationcomptefournis_montant_facturefournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat')),
                ('achat_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achatitems')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_fixing_detail', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fournisseur')),
            ],
        ),
    ]
