# Generated by Django 4.1.7 on 2023-04-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0017_fixingdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixingdetail',
            name='achat',
        ),
    ]
