# Generated by Django 4.1.7 on 2023-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0019_fixing_carrat_moyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixing',
            name='discompte',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixing',
            name='type',
            field=models.IntegerField(choices=[(1, 'Par barre'), (2, 'Global')], default=1),
            preserve_default=False,
        ),
    ]
