# Generated by Django 4.1.7 on 2023-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0021_fixing_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcomptefournis',
            name='solde_anterieur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
