# Generated by Django 4.1.7 on 2023-04-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation_fournisseur', '0022_operationcomptefournis_solde_anterieur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(choices=[(1, 'Entrée'), (2, 'Sortie')])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('devise', models.IntegerField(choices=[(1, 'GNF'), (2, 'USD')])),
                ('motif', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_caisse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
