# Generated by Django 4.1.7 on 2023-04-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0023_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixing',
            name='achat',
        ),
        migrations.RemoveField(
            model_name='fixing',
            name='carrat_moyen',
        ),
        migrations.RemoveField(
            model_name='fixing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fixing',
            name='type',
        ),
        migrations.AddField(
            model_name='fixingdetail',
            name='achat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixingdetail',
            name='fixing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.fixing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixingdetail',
            name='type_envoie',
            field=models.IntegerField(choices=[(1, 'Par barre'), (2, 'Global')], default=1),
            preserve_default=False,
        ),
    ]
