# Generated by Django 4.1.7 on 2023-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0025_alter_fixingdetail_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixingdetail',
            name='poids_select',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
