# Generated by Django 4.1.7 on 2023-05-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0029_achatitems_item_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingdetail',
            name='achat_items',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_fournisseur.achatitems'),
        ),
    ]
