# Generated by Django 4.1.7 on 2023-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0030_alter_fixingdetail_achat_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingdetail',
            name='achat_items',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
