# Generated by Django 4.1.7 on 2023-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0032_alter_fixingdetail_achat_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingdetail',
            name='type_envoie',
            field=models.IntegerField(choices=[(1, 'Par barre'), (2, 'Global'), (3, 'Par Poids')]),
        ),
    ]
