# Generated by Django 4.1.7 on 2023-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0034_alter_achatitems_carrat_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='representant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='carrat_moyen',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='achat',
            name='poids_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='achatitems',
            name='carrat_achat',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='achatitems',
            name='manquant',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='achatitems',
            name='poids_achat',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='carrat_moyen',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='operationcomptefournis',
            name='taux',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
