# Generated by Django 4.1.7 on 2023-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0039_alter_achat_carrat_moyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='carrat_moyen',
            field=models.FloatField(null=True),
        ),
    ]
