# Generated by Django 4.1.7 on 2023-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0041_alter_achat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixingdetail',
            name='ordre_validation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
