# Generated by Django 4.1.7 on 2023-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0042_fixingdetail_ordre_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingdetail',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
