# Generated by Django 4.1.7 on 2023-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0043_alter_fixingdetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixingdetail',
            name='carrat_moyen_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
