# Generated by Django 4.1.7 on 2023-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_fournisseur', '0044_fixingdetail_carrat_moyen_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixingdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
